name=roo_fonts_material
version=1.0.0
author=Dejwk <dejwk.oss@gmail.com>
maintainer=Dejwk <dejwk.oss@gmail.com>
sentence=Collection of Material Design fonts for use with dejwk/roo_display.
paragraph=See http://github.com/dejwk/roo_display.
category=Display
url=https://github.com/dejwk/roo_fonts_material
architectures=*
depends=roo_display
